//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteringApp.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meters
    {
        public int ID { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientSecondName { get; set; }
        public int ColdWaterMeter { get; set; }
        public int HotWaterMeter { get; set; }
        public System.DateTime Datetime { get; set; }
    }
}
