//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteringApp.General
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeteringAppEntities : DbContext
    {
        public static MeteringAppEntities _context;
        public MeteringAppEntities()
            : base("name=MeteringAppEntities")
        {
        }
    
        public static MeteringAppEntities GetContext() { if(_context == null) { _context = new MeteringAppEntities(); } return _context; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginHistory> LoginHistory { get; set; }
        public virtual DbSet<Meters> Meters { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
    }
}
